(async()=>{
  const API=window.SuraeAPI;let data={profiles:[],orders:[],transactions:[],products:[],settings:{},rates:[]},selectedOrder=null,selectedUser=null;
  const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=n=>Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2}),date=v=>v?new Date(v).toLocaleDateString('en-PH',{year:'numeric',month:'short',day:'numeric'}):'—';
  const gate=$('cloudAdminGate'),verifyBox=$('cloudAdminVerify'),loginBox=$('cloudAdminLoginBox'),msg=$('cloudAdminMessage');
  function showVerifying(){gate.hidden=false;verifyBox.hidden=false;loginBox.hidden=true;msg.textContent=''}
  function showLogin(message=''){gate.hidden=false;verifyBox.hidden=true;loginBox.hidden=false;msg.textContent=message}
  function hideGate(){gate.hidden=true;verifyBox.hidden=true;loginBox.hidden=true}
  async function load(){data=await API.adminSnapshot();$('adminModeLabel').textContent='SUPABASE LIVE';hideGate();renderAll()}
  async function requireAdmin(){showVerifying();if(!API.getSession()){showLogin();return false}try{await load();return true}catch(e){API.logout();showLogin(e.message||'Admin login required.');return false}}
  $('cloudAdminLogin').onclick=async()=>{const b=$('cloudAdminLogin');b.disabled=true;msg.textContent='';try{await API.login($('cloudAdminEmail').value.trim(),$('cloudAdminPassword').value);showVerifying();await load();$('cloudAdminPassword').value=''}catch(e){API.logout();showLogin(e.message||'Unable to sign in.')}finally{b.disabled=false}};
  document.querySelectorAll('[data-admin-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-admin-view]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.admin-view').forEach(v=>v.classList.remove('active'));$(`adminView${b.dataset.adminView[0].toUpperCase()+b.dataset.adminView.slice(1)}`)?.classList.add('active')});document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.querySelector(`[data-admin-view="${b.dataset.jump}"]`)?.click());
  function renderAll(){renderDashboard();renderOrders();renderCustomers();renderSettings()}
  function renderDashboard(){const open=data.orders.filter(o=>!['Completed','Cancelled','Rejected'].includes(o.status));$('statPlayers').textContent=data.profiles.length;$('statProducts').textContent=data.products.filter(p=>p.active&&Number(p.price)>0).length;$('statCredits').textContent=money(data.profiles.reduce((s,p)=>s+Number(p.credits||0),0));$('statOpenOrders').textContent=open.length;$('dashStoreStatus').textContent=data.settings.store_online===false?'OFFLINE':'ONLINE';$('dashAnnouncement').textContent=data.settings.announcement||'No active announcement.';$('dashCatalogCount').textContent=data.products.length;const latest=data.orders.slice(0,8);$('dashboardOrders').innerHTML=latest.map(o=>`<tr><td>${esc(o.invoice_no)}</td><td>${esc(o.customer_name)}</td><td>${esc(o.user_info||'—')}</td><td>${esc(o.game)} / ${esc(o.product_summary)}</td><td>₱${money(o.total_amount)}</td><td>${esc(o.status)}</td><td>${date(o.created_at)}</td></tr>`).join('');$('dashboardNoOrders').style.display=latest.length?'none':'block'}
  function filteredOrders(){const q=$('orderSearch').value.trim().toLowerCase(),st=$('orderStatusFilter').value;return data.orders.filter(o=>(!st||o.status===st)&&(!q||[o.invoice_no,o.customer_name,o.product_summary,o.game,o.account_number].some(v=>String(v||'').toLowerCase().includes(q))))}
  function renderOrders(){const list=filteredOrders();$('orderListBody').innerHTML=list.map(o=>`<tr><td>${esc(o.invoice_no)}</td><td>${esc(o.customer_name)}<br><small>${esc(o.account_number||'GUEST')}</small></td><td>${esc(o.game)} / ${esc(o.product_summary)}</td><td>₱${money(o.total_amount)}</td><td>${esc(o.payment_method)}<br><small>${o.proof_verified?'✓ VERIFIED':o.proof_path?'AWAITING VERIFICATION':'NO PROOF'}</small></td><td><span class="table-status ${String(o.status).toLowerCase().replace(/\s+/g,'-')}">${esc(o.status)}</span></td><td>${esc(o.handler||'Unassigned')}</td><td>${date(o.created_at)}</td><td><button class="table-action" data-open-order="${o.id}">OPEN</button></td></tr>`).join('');$('noOrdersList').style.display=list.length?'none':'block';['New Order','Processing','Completed','Cancelled'].forEach(st=>{const id={ 'New Order':'countNew','Processing':'countProcessing','Completed':'countCompleted','Cancelled':'countCancelled'}[st];$(id).textContent=data.orders.filter(o=>o.status===st).length});document.querySelectorAll('[data-open-order]').forEach(b=>b.onclick=()=>openOrder(b.dataset.openOrder));renderKanban()}
  function renderKanban(){document.querySelectorAll('.kanban-dropzone').forEach(z=>z.innerHTML='');for(const o of filteredOrders()){const z=document.querySelector(`[data-drop-status="${CSS.escape(o.status)}"]`);if(!z)continue;const c=document.createElement('article');c.className='kanban-card';c.draggable=!o.fulfillment_applied&&!['Cancelled','Rejected'].includes(o.status);c.dataset.orderId=o.id;c.innerHTML=`<strong>${esc(o.invoice_no)}</strong><span>${esc(o.customer_name)}</span><small>${esc(o.product_summary)}</small><b>₱${money(o.total_amount)}</b>`;c.onclick=()=>openOrder(o.id);c.ondragstart=e=>e.dataTransfer.setData('text/plain',o.id);z.appendChild(c)}document.querySelectorAll('[data-kanban-count]').forEach(x=>x.textContent=data.orders.filter(o=>o.status===x.dataset.kanbanCount).length)}
  document.querySelectorAll('.kanban-dropzone').forEach(z=>{z.ondragover=e=>e.preventDefault();z.ondrop=async e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain'),o=data.orders.find(x=>x.id===id);if(!o||o.status===z.dataset.dropStatus)return;try{await API.admin('update-order',{orderId:id,status:z.dataset.dropStatus,handler:o.handler,note:o.note,proofVerified:o.proof_verified});await load()}catch(err){alert(err.message)}}});
  $('orderSearch').oninput=renderOrders;$('orderStatusFilter').onchange=renderOrders;document.querySelectorAll('[data-filter-status]').forEach(b=>b.onclick=()=>{$('orderStatusFilter').value=b.dataset.filterStatus;renderOrders()});document.querySelectorAll('[data-order-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-order-view]').forEach(x=>x.classList.toggle('active',x===b));$('orderListView').classList.toggle('active',b.dataset.orderView==='list');$('orderKanbanView').classList.toggle('active',b.dataset.orderView==='kanban')});
  const modal=$('orderModal');async function openOrder(id=''){selectedOrder=id?data.orders.find(o=>o.id===id):null;$('orderModalTitle').textContent=selectedOrder?selectedOrder.invoice_no:'NEW INVOICE';$('orderId').value=selectedOrder?.id||'';$('orderCustomerName').value=selectedOrder?.customer_name||'';$('orderAccountNumber').value=selectedOrder?.account_number||'';$('orderUserInfo').value=selectedOrder?.user_info||'';$('orderGame').value=['MLBB','CODM','VALORANT','ROBLOX','HOK','OTHER'].includes(selectedOrder?.game)?selectedOrder.game:'OTHER';$('orderProduct').value=selectedOrder?.product_summary||'';$('orderAmount').value=selectedOrder?Number(selectedOrder.total_amount):'';$('orderPayment').value=selectedOrder?.payment_method||'Manual';$('orderStatus').value=selectedOrder?.status||'New Order';$('orderHandler').value=selectedOrder?.handler||'Unassigned';$('orderNote').value=selectedOrder?.note||'';const proofBox=$('adminPaymentProof');proofBox.hidden=!selectedOrder?.proof_path;if(selectedOrder?.proof_path){$('adminPaymentReference').textContent=selectedOrder.payment_reference||'—';$('adminApprovalStatus').textContent=selectedOrder.proof_verified?'PAYMENT VERIFIED':'AWAITING APPROVAL';$('adminApprovalMessage').textContent=selectedOrder.proof_verified?'Payment proof has been verified.':'Verify the screenshot before processing.';try{const r=await API.admin('proof-url',{orderId:selectedOrder.id});$('adminProofImage').src=r.url}catch{$('adminProofImage').removeAttribute('src')}}const deleteBtn=$('deleteOrder');deleteBtn.hidden=!selectedOrder;deleteBtn.style.display=selectedOrder?'block':'none';modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
  $('addOrder').onclick=()=>openOrder();document.querySelectorAll('[data-close-order-modal]').forEach(x=>x.onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});
  $('verifyPaymentProof').onclick=async()=>{if(!selectedOrder)return;try{await API.admin('update-order',{orderId:selectedOrder.id,status:selectedOrder.status,handler:$('orderHandler').value,note:$('orderNote').value,proofVerified:true});await load();await openOrder(selectedOrder.id)}catch(e){alert(e.message)}};
  $('unverifyPaymentProof').onclick=async()=>{if(!selectedOrder||selectedOrder.fulfillment_applied)return alert('Fulfilled orders cannot be marked unverified.');try{await API.admin('update-order',{orderId:selectedOrder.id,status:selectedOrder.status,handler:$('orderHandler').value,note:$('orderNote').value,proofVerified:false});await load();await openOrder(selectedOrder.id)}catch(e){alert(e.message)}};
  $('orderForm').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{if(selectedOrder){await API.admin('update-order',{orderId:selectedOrder.id,status:$('orderStatus').value,handler:$('orderHandler').value.trim()||'Unassigned',note:$('orderNote').value.trim(),proofVerified:selectedOrder.proof_verified})}else{await API.admin('manual-order',{order:{customerName:$('orderCustomerName').value.trim(),accountNumber:$('orderAccountNumber').value.trim(),userInfo:$('orderUserInfo').value.trim(),game:$('orderGame').value,product:$('orderProduct').value.trim(),amount:Number($('orderAmount').value),status:$('orderStatus').value,handler:$('orderHandler').value.trim(),note:$('orderNote').value.trim()}})}modal.classList.remove('open');await load()}catch(err){alert(err.message)}finally{b.disabled=false}};
  $('deleteOrder').onclick=async()=>{if(!selectedOrder)return;const invoice=selectedOrder.invoice_no;const typed=prompt(`This permanently deletes invoice ${invoice}.\n\nOrder items/events and its uploaded payment proof will also be deleted. Credit/wallet movements already applied are NOT reversed.\n\nType the invoice number to confirm:`);if(typed!==invoice)return;if(!confirm(`Permanently delete ${invoice}? This cannot be undone.`))return;const b=$('deleteOrder');b.disabled=true;try{await API.admin('delete-order',{orderId:selectedOrder.id});selectedOrder=null;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');await load()}catch(e){alert(e.message)}finally{b.disabled=false}};
  function renderCustomers(){const q=$('adminSearch').value.trim().toLowerCase(),list=data.profiles.filter(u=>!q||[u.name,u.email,u.account_number,u.mobile].some(v=>String(v||'').toLowerCase().includes(q)));$('adminPlayers').innerHTML=list.map(u=>`<tr><td><div class="player-cell"><b>${esc(u.name)}</b><small>${esc(u.email)}</small></div></td><td>${esc(u.account_number)}</td><td>₱${money(u.credits)}</td><td><span class="table-status ${String(u.status).toLowerCase().replace(/\s+/g,'-')}">${esc(u.status)}</span></td><td>${date(u.created_at)}</td><td><button class="table-action" data-manage="${u.user_id}">MANAGE</button></td></tr>`).join('');$('adminNoPlayers').style.display=list.length?'none':'block';document.querySelectorAll('[data-manage]').forEach(b=>b.onclick=()=>openManage(b.dataset.manage));$('adminTransactions').innerHTML=data.transactions.slice(0,50).map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(data.profiles.find(p=>p.user_id===t.user_id)?.account_number||'—')}</td><td>${esc(t.type)}</td><td class="${Number(t.amount)>=0?'amount-positive':'amount-negative'}">${Number(t.amount)>=0?'+':''}₱${money(t.amount)}</td><td>${esc(t.source)}</td><td>${date(t.created_at)}</td></tr>`).join('');$('adminNoTransactions').style.display=data.transactions.length?'none':'block'}$('adminSearch').oninput=renderCustomers;$('createDemoPlayer').hidden=true;
  const manage=$('managePlayerModal');function openManage(id){selectedUser=data.profiles.find(p=>p.user_id===id);if(!selectedUser)return;$('managePlayerName').textContent=selectedUser.name.toUpperCase();$('manageAccountNumber').textContent=selectedUser.account_number;$('manageEmail').textContent=selectedUser.email;$('manageCredits').textContent=money(selectedUser.credits);$('adminAccountStatus').value=selectedUser.status;$('adminManageMessage').textContent='';manage.classList.add('open');manage.setAttribute('aria-hidden','false')}document.querySelectorAll('[data-close-admin-modal]').forEach(x=>x.onclick=()=>{manage.classList.remove('open');manage.setAttribute('aria-hidden','true')});
  $('applyCreditAdjustment').onclick=async()=>{if(!selectedUser)return;const amount=Number($('adminCreditAmount').value),reason=$('adminCreditReason').value.trim()||'Manual adjustment';try{await API.admin('credit-adjust',{userId:selectedUser.user_id,amount,reason});$('adminManageMessage').textContent='Credit adjustment applied.';await load();openManage(selectedUser.user_id)}catch(e){$('adminManageMessage').textContent=e.message}};$('saveAccountStatus').onclick=async()=>{if(!selectedUser)return;try{await API.admin('user-status',{userId:selectedUser.user_id,status:$('adminAccountStatus').value});await load();openManage(selectedUser.user_id)}catch(e){$('adminManageMessage').textContent=e.message}};
  $('deletePlayerAccount').onclick=async()=>{if(!selectedUser)return;const account=selectedUser.account_number||selectedUser.email;const typed=prompt(`This permanently deletes the player/customer login and profile for ${account}.\n\nExisting invoices will be retained for business records and become detached from the deleted login.\n\nType the account number exactly to confirm:`);if(typed!==String(selectedUser.account_number||''))return;if(!confirm(`Permanently delete ${selectedUser.name} (${account})? This cannot be undone.`))return;const b=$('deletePlayerAccount');b.disabled=true;$('adminManageMessage').textContent='Deleting account…';try{await API.admin('delete-user',{userId:selectedUser.user_id});selectedUser=null;manage.classList.remove('open');manage.setAttribute('aria-hidden','true');await load()}catch(e){$('adminManageMessage').textContent=e.message}finally{b.disabled=false}};
  function renderSettings(){const s=data.settings;$('settingStoreOnline').checked=s.store_online!==false;$('settingAnnouncement').value=s.announcement||'';$('settingWallet').checked=s.allow_wallet!==false;$('settingBank').checked=s.allow_bank!==false;$('settingGCash').checked=s.allow_gcash!==false;$('settingPayMaya').checked=s.allow_paymaya!==false;$('resetCatalog').hidden=true;$('resetCatalog').closest('.settings-card')?.querySelector('p')?.replaceChildren(document.createTextNode('Production catalog is stored in Supabase and is never reset from the browser.'))}
  $('saveStoreSettings').onclick=async()=>{try{await API.admin('settings-save',{settings:{storeOnline:$('settingStoreOnline').checked,announcement:$('settingAnnouncement').value.trim(),allowWallet:$('settingWallet').checked,allowBank:$('settingBank').checked,allowGCash:$('settingGCash').checked,allowPayMaya:$('settingPayMaya').checked}});$('settingsMessage').textContent='Settings saved to Supabase.';await load()}catch(e){$('settingsMessage').textContent=e.message}};
  await requireAdmin();if(location.hash==='#products')document.querySelector('[data-admin-view="products"]')?.click();
})();
