(async()=>{
  const A=window.SuraeStore,C=window.SuraeCatalog,Cart=window.SuraeCart,P=window.SuraeProofs,API=window.SuraeAPI;await Promise.all([A.ready,C.ready]);
  const money=n=>Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2}),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const randomRequestId=()=>{const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')};const ATTEMPT_KEY='surae_checkout_attempt_v1';function requestIdFor(fingerprint){try{const prev=JSON.parse(sessionStorage.getItem(ATTEMPT_KEY)||'null');if(prev?.fingerprint===fingerprint&&/^[a-f0-9]{64}$/i.test(prev.requestId||''))return prev.requestId}catch{}const requestId=randomRequestId();try{sessionStorage.setItem(ATTEMPT_KEY,JSON.stringify({fingerprint,requestId}))}catch{}return requestId}function clearAttempt(){try{sessionStorage.removeItem(ATTEMPT_KEY)}catch{}}
  const params=new URLSearchParams(location.search),buy=params.get('buy');if(buy){Cart.add(buy,1);history.replaceState({},'',location.pathname)}
  let user=A.getCurrentUser(),payment='';const settings=C.getSettings(),methods=[];if(settings.allowBank!==false)methods.push('Bank');if(settings.allowGCash!==false)methods.push('GCash');if(settings.allowPayMaya!==false)methods.push('PayMaya');if(user&&settings.allowWallet!==false)methods.push('Surae Credits');
  const name=document.getElementById('checkoutName'),email=document.getElementById('checkoutEmail'),mobile=document.getElementById('checkoutMobile');if(user){name.value=user.name||'';email.value=user.email||'';mobile.value=user.mobile||'';['guestNameField','guestEmailField','guestMobileField'].forEach(id=>document.getElementById(id).hidden=true);document.getElementById('customerHint').textContent=`Logged in as ${user.name}. Surae Credits are available as a payment option.`}else document.getElementById('customerHint').textContent='No account required. Guest customers can pay by Bank, GCash or PayMaya.';
  const opts=document.getElementById('paymentOptions');opts.innerHTML=methods.map(m=>`<label class="payment-option ${m==='Surae Credits'?'credits':''}"><input type="radio" name="paymethod" value="${m}"><span>${m}</span></label>`).join('');opts.addEventListener('change',e=>{if(e.target.name==='paymethod'){payment=e.target.value;updatePaymentUI()}});
  function cartLines(){const products=C.getCatalog();return Cart.getItems().map(ci=>{const p=products.find(x=>x.id===ci.productId&&x.active!==false);return p&&Number(p.price)>0?{...ci,p,subtotal:Number(p.price)*ci.qty}:null}).filter(Boolean)}function total(){return cartLines().reduce((s,x)=>s+x.subtotal,0)}
  function render(){const lines=cartLines(),host=document.getElementById('checkoutItems');host.innerHTML=lines.map(x=>`<div class="checkout-item"><div><h3>${esc(x.p.name)}</h3><small>${esc(x.p.game)} • ${esc(x.p.region)} • ₱${money(x.p.price)} each</small></div><div class="checkout-item-actions"><input type="number" min="1" max="99" value="${x.qty}" data-qty="${esc(x.p.id)}"><strong>₱${money(x.subtotal)}</strong><button class="checkout-remove" data-remove="${esc(x.p.id)}" type="button">REMOVE</button></div></div>`).join('');document.getElementById('emptyCart').hidden=!!lines.length;document.getElementById('checkoutTotal').textContent='₱'+money(total());host.querySelectorAll('[data-qty]').forEach(i=>i.onchange=()=>{Cart.setQty(i.dataset.qty,Math.max(1,Math.min(99,Number(i.value)||1)));render()});host.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{Cart.remove(b.dataset.remove);render()});updatePaymentUI()}
  function updatePaymentUI(){const wallet=payment==='Surae Credits';document.getElementById('externalPaymentFields').hidden=wallet;const wb=document.getElementById('walletBox');wb.hidden=!wallet;if(user)document.getElementById('walletBalance').textContent='₱'+money(user.credits||0);document.getElementById('checkoutMessage').textContent=payment?(wallet?'Credits will be deducted only after you click PLACE ORDER.':'Upload your payment proof to submit the order.'):'Select a payment method to continue.'}
  function showTopup(required,balance){document.getElementById('topupNeededText').textContent=`Your cart total is ₱${money(required)}, but your available balance is ₱${money(balance)}. Top up your Surae Credits first or choose another payment method.`;const m=document.getElementById('topupNeeded');m.classList.add('open');m.setAttribute('aria-hidden','false')};document.getElementById('closeTopupNeeded').onclick=()=>{const m=document.getElementById('topupNeeded');m.classList.remove('open');m.setAttribute('aria-hidden','true')};
  document.getElementById('placeOrder').onclick=async()=>{const btn=document.getElementById('placeOrder'),msg=document.getElementById('checkoutMessage');if(btn.disabled)return;const lines=cartLines();if(!lines.length){msg.textContent='Your cart is empty.';msg.className='checkout-message error';return}if(!payment){msg.textContent='Choose a payment method.';msg.className='checkout-message error';return}const customerName=user?.name||name.value.trim(),customerEmail=user?.email||email.value.trim(),customerMobile=user?.mobile||mobile.value.trim(),userInfo=document.getElementById('checkoutUserInfo').value.trim();if(!customerName||!customerEmail||!customerMobile){msg.textContent='Name, email and mobile number are required.';msg.className='checkout-message error';return}if(!userInfo){msg.textContent='Game account / user info is required.';msg.className='checkout-message error';return}
    let proof=null,reference='';if(payment!=='Surae Credits'){reference=document.getElementById('checkoutReference').value.trim();proof=document.getElementById('checkoutProof').files?.[0]||null;const confirmed=document.getElementById('checkoutProofConfirm').checked;if(!reference){msg.textContent='Payment reference number is required.';msg.className='checkout-message error';return}if(!confirmed){msg.textContent='Please confirm the reference number is visible in the screenshot.';msg.className='checkout-message error';return}try{P.validateFile(proof)}catch(e){msg.textContent=e.message;msg.className='checkout-message error';return}}
    const orderItems=lines.map(x=>({productId:x.p.id,qty:x.qty}));const fingerprint=JSON.stringify({payment,customerName,customerEmail,customerMobile,userInfo,reference,items:orderItems});const requestId=requestIdFor(fingerprint);btn.disabled=true;btn.textContent='PROCESSING…';try{const result=await API.checkout({requestId,orderType:'store-purchase',customerName,customerEmail,customerMobile,userInfo,paymentMethod:payment,paymentReference:reference,items:orderItems},proof);clearAttempt();Cart.clear();await Promise.all([A.refresh().catch(()=>null),C.refresh().catch(()=>null)]);user=A.getCurrentUser();render();const o=result.order;const receiptNote=result.receiptAccepted?` A receipt has been queued for delivery to <strong>${esc(customerEmail)}</strong>.`:` <strong>Save this invoice number.</strong> We could not confirm receipt-email delivery; contact support if the email does not arrive.`;msg.innerHTML=`Order <strong>${esc(o.invoiceNo)}</strong> submitted successfully. Status: <strong>${esc(o.status)}</strong>.${receiptNote}${o.trackingUrl?`<br><a href="${esc(o.trackingUrl)}">TRACK YOUR ORDER</a>`:''}`;msg.className='checkout-message success'}catch(e){if(e.code==='INSUFFICIENT_CREDITS'){showTopup(e.required||total(),e.balance||user?.credits||0)}else{msg.textContent=e.message||'Unable to place the order.';msg.className='checkout-message error'}}finally{btn.disabled=false;btn.textContent='PLACE ORDER'}};
  render();
})();
