(async()=>{
  const A=window.SuraeStore,O=window.SuraeOrders,P=window.SuraeProofs,API=window.SuraeAPI,C=window.SuraeCatalog;await Promise.all([A.ready,C.ready]);let user=A.getCurrentUser();if(!user){location.replace('index.html');return}
  const money=n=>Number(n||0).toLocaleString('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2}),date=v=>v?new Date(v).toLocaleDateString('en-PH',{year:'numeric',month:'short',day:'numeric'}):'—',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const randomRequestId=()=>{const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')};const TOPUP_ATTEMPT_KEY='surae_topup_attempt_v1';function topupRequestFor(fingerprint){try{const prev=JSON.parse(sessionStorage.getItem(TOPUP_ATTEMPT_KEY)||'null');if(prev?.fingerprint===fingerprint&&/^[a-f0-9]{64}$/i.test(prev.requestId||''))return prev.requestId}catch{}const requestId=randomRequestId();try{sessionStorage.setItem(TOPUP_ATTEMPT_KEY,JSON.stringify({fingerprint,requestId}))}catch{}return requestId}function clearTopupAttempt(){try{sessionStorage.removeItem(TOPUP_ATTEMPT_KEY)}catch{}}
  async function refresh(){await A.refresh();user=A.getCurrentUser();if(!user){location.replace('index.html');return}O.setOrders(A.getOrders());render()}
  function render(){document.getElementById('navPlayerName').textContent=user.name;document.getElementById('navPlayerCredits').textContent='₱'+money(user.credits);document.getElementById('heroPlayerName').textContent=(user.name||'PLAYER').split(' ')[0].toUpperCase();document.getElementById('playerInitial').textContent=(user.name||'S').charAt(0).toUpperCase();document.getElementById('playerName').textContent=user.name;document.getElementById('playerEmail').textContent=user.email;document.getElementById('playerMobile').textContent=user.mobile;document.getElementById('playerAccountNumber').textContent=user.accountNumber;document.getElementById('playerCredits').textContent=money(user.credits);document.getElementById('playerStatus').textContent=String(user.status||'Active').toUpperCase();document.getElementById('playerSince').textContent=date(user.createdAt);
    const tx=A.getTransactions();document.getElementById('playerTransactions').innerHTML=tx.map(t=>`<tr><td>${esc(t.id)}</td><td>${esc(t.type)}</td><td class="${Number(t.amount)>=0?'amount-positive':'amount-negative'}">${Number(t.amount)>=0?'+':''}₱${money(t.amount)}</td><td>Completed</td><td>${date(t.createdAt)}</td></tr>`).join('');document.getElementById('playerNoTransactions').style.display=tx.length?'none':'block';
    const orders=A.getOrders().map(O.mapFromCloud);document.getElementById('playerInvoices').innerHTML=orders.map(o=>`<tr><td>${esc(o.id)}</td><td>${esc(o.product)}</td><td>₱${money(o.amount)}</td><td><span class="table-status ${String(o.status).toLowerCase().replace(/\s+/g,'-')}">${esc(o.status)}</span></td><td>${date(o.createdAt)}</td></tr>`).join('');document.getElementById('playerNoInvoices').style.display=orders.length?'none':'block';
  }
  function preview(input,box,img,name){const file=input.files?.[0];if(!file){box.hidden=true;return}try{P.validateFile(file)}catch(e){input.value='';box.hidden=true;alert(e.message);return}const url=URL.createObjectURL(file);img.onload=()=>URL.revokeObjectURL(url);img.src=url;name.textContent=`${file.name} • ${(file.size/1024/1024).toFixed(2)} MB`;box.hidden=false}
  const topupSelect=document.getElementById('topUpPaymentMethod'),shopSettings=C.getSettings(),topupMethods=[];if(shopSettings.allowBank!==false)topupMethods.push('Bank');if(shopSettings.allowGCash!==false)topupMethods.push('GCash');if(shopSettings.allowPayMaya!==false)topupMethods.push('PayMaya');topupSelect.innerHTML='<option value="">Select payment method</option>'+topupMethods.map(m=>`<option value="${m}">${m}</option>`).join('');
  const topModal=document.getElementById('topUpModal'),openTop=()=>{topModal.classList.add('open');topModal.setAttribute('aria-hidden','false')};document.getElementById('openTopUp').onclick=openTop;if(location.hash==='#topup')setTimeout(openTop,0);document.querySelectorAll('[data-close-topup]').forEach(x=>x.onclick=()=>{topModal.classList.remove('open');topModal.setAttribute('aria-hidden','true')});document.querySelectorAll('[data-amount]').forEach(b=>b.onclick=()=>document.getElementById('playerTopUpAmount').value=b.dataset.amount);
  const proof=document.getElementById('topUpProof');proof.onchange=()=>preview(proof,document.getElementById('topUpProofPreview'),document.getElementById('topUpProofImage'),document.getElementById('topUpProofName'));
  document.getElementById('confirmPlayerTopUp').onclick=async()=>{const btn=document.getElementById('confirmPlayerTopUp'),msg=document.getElementById('playerTopUpMessage');if(btn.disabled)return;const amount=Number(document.getElementById('playerTopUpAmount').value),method=document.getElementById('topUpPaymentMethod').value,reference=document.getElementById('topUpReference').value.trim(),file=proof.files?.[0]||null,confirmed=document.getElementById('topUpProofConfirm').checked;if(!Number.isFinite(amount)||amount<50){msg.textContent='Minimum top-up is ₱50.';msg.className='portal-note error';return}if(!['Bank','GCash','PayMaya'].includes(method)){msg.textContent='Please select Bank, GCash or PayMaya.';msg.className='portal-note error';return}if(!reference||!file||!confirmed){msg.textContent='Reference number, payment screenshot and confirmation are required.';msg.className='portal-note error';return}try{P.validateFile(file)}catch(e){msg.textContent=e.message;msg.className='portal-note error';return}const requestId=topupRequestFor(JSON.stringify({amount,method,reference}));btn.disabled=true;btn.textContent='SUBMITTING…';try{const r=await API.checkout({requestId,orderType:'wallet-topup',amount,paymentMethod:method,paymentReference:reference,userInfo:'Wallet Top-Up',items:[]},file);clearTopupAttempt();msg.textContent=`Top-up ${r.order.invoiceNo} submitted. Credits are added only after Admin verifies and completes the request. ${r.receiptAccepted?`A receipt has been queued for ${user.email}.`:'Keep this invoice number; receipt-email delivery could not be confirmed.'}`;msg.className='portal-note success';document.getElementById('playerTopUpAmount').value='';document.getElementById('topUpPaymentMethod').value='';document.getElementById('topUpReference').value='';document.getElementById('topUpProofConfirm').checked=false;proof.value='';document.getElementById('topUpProofPreview').hidden=true;await refresh()}catch(e){msg.textContent=e.message||'Unable to submit top-up.';msg.className='portal-note error'}finally{btn.disabled=false;btn.textContent='SUBMIT TOP-UP REQUEST'}};
  document.getElementById('copyPlayerAccount').onclick=async()=>{try{await navigator.clipboard.writeText(user.accountNumber)}catch{}};document.getElementById('playerLogout').onclick=()=>{A.logout();location.href='index.html'};
  render();
})();
