import { createClient } from 'npm:@supabase/supabase-js@2'
import { ANON_KEY, SUPABASE_URL, service, anonClient, cors, json, clean, money, invoiceNo, sha256, currentUser, requireStaff, safeError } from '../_shared/common.ts'
import { sendMail, receiptHtml, statusHtml } from '../_shared/email.ts'

const METHODS=new Set(['Bank','GCash','PayMaya'])
const ALLOWED_MIME=new Set(['image/png','image/jpeg','image/webp'])
const MAX_PROOF=5*1024*1024
const validEmail=(v:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/i.test(v)
const validRequestId=(v:string)=>/^[a-f0-9]{64}$/i.test(v)
const normRef=(v:string)=>v.replace(/[^a-z0-9]/gi,'').toUpperCase()
const GAME_SET=new Set(['MLBB','CODM','HOK','VALORANT','ROBLOX'])
const STOCK_SET=new Set(['Available','Pre-order','Out of Stock'])
const CATALOG_BY_GAME:Record<string,Set<string>>={MLBB:new Set(['regular','skin-gifting']),CODM:new Set(['regular']),HOK:new Set(['regular','skin-gifting']),VALORANT:new Set(['regular']),ROBLOX:new Set(['regular'])}
const PILOTING_SCHEMA:any={MLBB:{unit:'star',ranks:['Warrior','Elite','Master','Grandmaster','Epic','Legend','Mythic','Mythical Honor','Mythical Glory','Mythical Immortal']},CODM:{unit:'point',ranks:['Rookie','Veteran','Elite','Pro','Master','Grandmaster','Legendary']}}

async function parse(req:Request){
  const ct=req.headers.get('content-type')||''
  if(ct.includes('multipart/form-data')){const form=await req.formData();const raw=String(form.get('payload')||'{}');return {body:JSON.parse(raw),file:form.get('proof') instanceof File?form.get('proof') as File:null,signature:form.get('signature') instanceof File?form.get('signature') as File:null}}
  return {body:await req.json(),file:null,signature:null}
}
function publicOrder(o:any){return {id:o.id,invoiceNo:o.invoice_no,status:o.status,amount:Number(o.total_amount),payment:o.payment_method,createdAt:o.created_at,trackingUrl:o.trackingUrl||'',email:o.customer_email}}
async function getProfile(sb:any,userId:string){const {data,error}=await sb.from('profiles').select('*').eq('user_id',userId).maybeSingle();if(error)throw error;return data}
async function bootstrap(sb:any){
  const [{data:products,error:pe},{data:settings,error:se},{data:rates,error:re}]=await Promise.all([
    sb.from('products').select('id,game,region,name,category,description,price,active,stock_status,catalog_type').eq('active',true).order('id'),
    sb.from('store_settings').select('*').eq('singleton',true).single(),
    sb.from('piloting_rates').select('*').order('game').order('sort_order')
  ]);if(pe)throw pe;if(se)throw se;if(re)throw re;return {products:products||[],settings,rates:rates||[]}
}
async function authLogin(body:any){
  let identity=clean(body.identity,180).toLowerCase();const password=String(body.password||'');if(!identity||password.length<1)throw Object.assign(new Error('Email/account number and password are required.'),{status:400,code:'VALIDATION'});
  let email=identity;const sb=service();
  if(!identity.includes('@')){const {data}=await sb.from('profiles').select('email').ilike('account_number',identity).maybeSingle();if(!data)throw Object.assign(new Error('Incorrect account/email or password.'),{status:401,code:'INVALID_LOGIN'});email=data.email}
  const ac=anonClient();const {data,error}=await ac.auth.signInWithPassword({email,password});if(error||!data.session)throw Object.assign(new Error('Incorrect account/email or password.'),{status:401,code:'INVALID_LOGIN'});
  const profile=await getProfile(sb,data.user.id);return {session:data.session,profile}
}
async function authRegister(body:any){
  const name=clean(body.name,120),email=clean(body.email,180).toLowerCase(),mobile=clean(body.mobile,40),password=String(body.password||'');
  if(!name||!email||!mobile)throw Object.assign(new Error('Name, email and mobile number are required.'),{status:400,code:'VALIDATION'});if(password.length<8)throw Object.assign(new Error('Password must be at least 8 characters.'),{status:400,code:'VALIDATION'});
  const ac=anonClient();const {data,error}=await ac.auth.signUp({email,password,options:{data:{name,mobile}}});if(error)throw Object.assign(new Error(error.message),{status:400,code:'AUTH'});
  let profile=null;if(data.user)profile=await getProfile(service(),data.user.id);return {session:data.session,profile,needsEmailConfirmation:!data.session}
}
async function resolveItems(sb:any,items:any[]){
  if(!Array.isArray(items)||!items.length)throw Object.assign(new Error('Your cart is empty.'),{status:400,code:'EMPTY_CART'});
  const qtyById=new Map<string,number>();for(const raw of items.slice(0,100)){const productId=clean(raw?.productId,100),qty=Math.floor(Number(raw?.qty)||1);if(!productId||qty<1||qty>99)throw Object.assign(new Error('Invalid cart quantity.'),{status:400,code:'CART_INVALID'});const combined=(qtyById.get(productId)||0)+qty;if(combined>99)throw Object.assign(new Error('Maximum quantity is 99 per product per order.'),{status:400,code:'CART_QTY_LIMIT'});qtyById.set(productId,combined)}
  const normalized=[...qtyById].map(([productId,qty])=>({productId,qty}));if(!normalized.length||normalized.length>50)throw Object.assign(new Error('Your cart contains too many different products.'),{status:400,code:'CART_INVALID'});
  const ids=normalized.map(x=>x.productId);const {data,error}=await sb.from('products').select('*').in('id',ids);if(error)throw error;const map=new Map((data||[]).map((p:any)=>[p.id,p]));
  const lines=[];for(const x of normalized){const p:any=map.get(x.productId);if(!p||!p.active||Number(p.price)<=0||p.stock_status==='Out of Stock')throw Object.assign(new Error('One or more products are unavailable. Refresh your cart.'),{status:409,code:'PRODUCT_CHANGED'});if(p.game==='MLBB'&&p.region==='US'&&p.catalog_type==='skin-gifting')throw Object.assign(new Error('MLBB US skin gifting is unavailable.'),{status:409,code:'UNAVAILABLE'});const subtotal=money(Number(p.price)*x.qty);lines.push({productId:p.id,name:p.name,game:p.game,region:p.region,qty:x.qty,unitPrice:Number(p.price),subtotal,catalogType:p.catalog_type})}
  return lines
}
function validateProof(file:File|null,reference:string){if(!reference)throw Object.assign(new Error('Payment reference number is required.'),{status:400,code:'REFERENCE_REQUIRED'});if(!file)throw Object.assign(new Error('Payment screenshot is required.'),{status:400,code:'PROOF_REQUIRED'});if(file.size<=0||file.size>MAX_PROOF)throw Object.assign(new Error('Payment screenshot must be 5 MB or smaller.'),{status:400,code:'PROOF_SIZE'});if(!ALLOWED_MIME.has(file.type))throw Object.assign(new Error('Payment screenshot must be JPG, PNG or WebP.'),{status:400,code:'PROOF_TYPE'})}
function validImageSignature(bytes:Uint8Array,type:string){if(type==='image/png')return bytes.length>8&&bytes[0]===0x89&&bytes[1]===0x50&&bytes[2]===0x4e&&bytes[3]===0x47&&bytes[4]===0x0d&&bytes[5]===0x0a&&bytes[6]===0x1a&&bytes[7]===0x0a;if(type==='image/jpeg')return bytes.length>3&&bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff;if(type==='image/webp')return bytes.length>12&&String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';return false}
async function uploadProof(sb:any,file:File,invoice:string){const ext=file.type==='image/png'?'png':file.type==='image/webp'?'webp':'jpg';const path=`${new Date().toISOString().slice(0,10)}/${invoice}-${crypto.randomUUID()}.${ext}`;const bytes=new Uint8Array(await file.arrayBuffer());if(!validImageSignature(bytes,file.type))throw Object.assign(new Error('The uploaded file content does not match a supported image format.'),{status:400,code:'PROOF_CONTENT_INVALID'});const {error}=await sb.storage.from('payment-proofs').upload(path,bytes,{contentType:file.type,upsert:false});if(error)throw error;return path}
async function sendReceiptBestEffort(sb:any,order:any,items:any[],trackingToken=''){try{const sent=await sendMail(order.customer_email,`Surae receipt • ${order.invoice_no}`,receiptHtml(order,items,trackingToken));if(sent?.id)await sb.from('orders').update({receipt_email_id:sent.id}).eq('id',order.id);return sent}catch(e){console.error('receipt email failed',e);return null}}
async function checkout(req:Request,body:any,file:File|null){
  const sb=service(),{user}=await currentUser(req);const registered=!!user;const orderType=clean(body.orderType||'store-purchase',30);const payment=clean(body.paymentMethod,30);const userInfo=clean(body.userInfo,250);const requestId=clean(body.requestId,80).toLowerCase();if(!validRequestId(requestId))throw Object.assign(new Error('Invalid checkout request. Please refresh and try again.'),{status:400,code:'REQUEST_ID_INVALID'});const requestHash=await sha256(requestId);let profile:any=null;
  const {data:settings,error:settingsError}=await sb.from('store_settings').select('*').eq('singleton',true).single();if(settingsError)throw settingsError;if(!settings?.store_online)throw Object.assign(new Error('The store is temporarily offline.'),{status:503,code:'STORE_OFFLINE'});
  if(registered)profile=await getProfile(sb,user!.id);if(registered&&profile?.status!=='Active')throw Object.assign(new Error('This player account is not active.'),{status:403,code:'ACCOUNT_INACTIVE'});
  const customerName=registered?profile.name:clean(body.customerName,120),customerEmail=registered?profile.email:clean(body.customerEmail,180).toLowerCase(),customerMobile=registered?profile.mobile:clean(body.customerMobile,40);
  if(!customerName||!customerEmail||!customerMobile)throw Object.assign(new Error('Name, email and mobile number are required.'),{status:400,code:'VALIDATION'});if(!validEmail(customerEmail))throw Object.assign(new Error('Enter a valid email address for your receipt.'),{status:400,code:'EMAIL_INVALID'});
  const inv=invoiceNo();let lines:any[]=[],total=0,game='OTHER',region='GLOBAL',summary='',catalogType='regular';
  if(orderType==='wallet-topup'){
    if(!registered)throw Object.assign(new Error('Please log in to top up Surae Credits.'),{status:401,code:'LOGIN_REQUIRED'});total=money(body.amount);if(total<50||total>100000)throw Object.assign(new Error('Top-up amount must be between ₱50 and ₱100,000.'),{status:400,code:'INVALID_AMOUNT'});game='WALLET';summary=`Surae Credits Top-Up ₱${total.toFixed(2)}`;catalogType='wallet';
  } else {
    lines=await resolveItems(sb,body.items);total=money(lines.reduce((s,x)=>s+x.subtotal,0));const games=[...new Set(lines.map(x=>x.game))],regions=[...new Set(lines.map(x=>x.region))],catalogs=[...new Set(lines.map(x=>x.catalogType))];if(games.length!==1)throw Object.assign(new Error('Products from different games must be checked out separately so the correct game account is used.'),{status:409,code:'MIXED_GAME_CART'});if(regions.length!==1)throw Object.assign(new Error('Products from different servers/regions must be checked out separately.'),{status:409,code:'MIXED_REGION_CART'});if(catalogs.length!==1)throw Object.assign(new Error('Skin Gifting and regular store products must be checked out separately.'),{status:409,code:'MIXED_CATALOG_CART'});game=games[0];region=regions[0];summary=lines.map(x=>`${x.qty}× ${x.name}`).join(' + ');catalogType=catalogs[0];if(!userInfo)throw Object.assign(new Error('Game account / user info is required.'),{status:400,code:'USER_INFO_REQUIRED'});
  }
  if(payment==='Surae Credits'){
    if(!registered||orderType==='wallet-topup'||settings.allow_wallet===false)throw Object.assign(new Error('Surae Credits cannot be used for this transaction.'),{status:400,code:'PAYMENT_NOT_ALLOWED'});
    const {data,error}=await sb.rpc('create_credit_order',{p_user_id:user!.id,p_invoice_no:inv,p_customer_name:customerName,p_customer_email:customerEmail,p_customer_mobile:customerMobile,p_account_number:profile.account_number,p_order_type:catalogType==='skin-gifting'?'skin-gifting':'store-purchase',p_game:game,p_region:region,p_user_info:userInfo,p_product_summary:summary,p_total:total,p_catalog_type:catalogType,p_client_request_hash:requestHash,p_items:lines});
    if(error){if(String(error.message).includes('INSUFFICIENT_CREDITS')){const {data:existing}=await sb.from('orders').select('*').eq('client_request_hash',requestHash).eq('user_id',user!.id).maybeSingle();if(existing){const fresh=await getProfile(sb,user!.id);return {order:publicOrder(existing),balance:Number(fresh?.credits||0),receiptAccepted:Boolean(existing.receipt_email_id),idempotent:true}}const fresh=await getProfile(sb,user!.id);throw Object.assign(new Error('Insufficient Surae Credits.'),{status:409,code:'INSUFFICIENT_CREDITS',balance:Number(fresh?.credits||0),required:total})}if((error as any)?.code==='23505'){const {data:existing}=await sb.from('orders').select('*').eq('client_request_hash',requestHash).eq('user_id',user!.id).maybeSingle();if(existing){const fresh=await getProfile(sb,user!.id);return {order:publicOrder(existing),balance:Number(fresh?.credits||0),receiptAccepted:Boolean(existing.receipt_email_id),idempotent:true}}}throw error}
    const o=Array.isArray(data)?data[0]:data;const mail=await sendReceiptBestEffort(sb,o,lines);const fresh=await getProfile(sb,user!.id);return {order:publicOrder(o),balance:Number(fresh.credits),receiptAccepted:Boolean(mail?.id)}
  }
  if(!METHODS.has(payment))throw Object.assign(new Error('Choose Bank, GCash or PayMaya.'),{status:400,code:'PAYMENT_NOT_ALLOWED'});
  const methodEnabled=payment==='Bank'?settings.allow_bank:payment==='GCash'?settings.allow_gcash:settings.allow_paymaya;if(methodEnabled===false)throw Object.assign(new Error(`${payment} is currently unavailable. Choose another payment method.`),{status:409,code:'PAYMENT_UNAVAILABLE'});
  const reference=clean(body.paymentReference,120);
  const {data:existingRequest}=await sb.from('orders').select('*').eq('client_request_hash',requestHash).maybeSingle();
  if(existingRequest){const sameOwner=registered?existingRequest.user_id===user!.id:(existingRequest.customer_type==='guest'&&String(existingRequest.customer_email||'').toLowerCase()===customerEmail&&normRef(String(existingRequest.payment_reference||''))===normRef(reference));if(!sameOwner)throw Object.assign(new Error('This checkout request is already associated with another transaction.'),{status:409,code:'REQUEST_ID_REUSED'});const trackingUrl=!registered&&existingRequest.tracking_enabled&&Deno.env.get('SITE_URL')?`${Deno.env.get('SITE_URL')!.replace(/\/$/,'')}/track-order.html?t=${requestId}`:'';return {order:{...publicOrder(existingRequest),trackingUrl},receiptAccepted:Boolean(existingRequest.receipt_email_id),idempotent:true}}
  validateProof(file,reference);let proofPath='';
  try{
    proofPath=await uploadProof(sb,file!,inv);let trackingToken='',trackingHash=null,trackingEnabled=!registered;if(trackingEnabled){trackingToken=requestId;trackingHash=await sha256(trackingToken)}
    const {data,error}=await sb.rpc('create_external_order',{p_invoice_no:inv,p_user_id:user?.id||null,p_customer_type:registered?'registered':'guest',p_customer_name:customerName,p_customer_email:customerEmail,p_customer_mobile:customerMobile,p_account_number:profile?.account_number||'',p_order_type:orderType==='wallet-topup'?'wallet-topup':(catalogType==='skin-gifting'?'skin-gifting':'store-purchase'),p_game:game,p_region:region,p_user_info:userInfo,p_product_summary:summary,p_total:total,p_payment_method:payment,p_payment_reference:reference,p_proof_path:proofPath,p_catalog_type:catalogType,p_client_request_hash:requestHash,p_tracking_token_hash:trackingHash,p_tracking_enabled:trackingEnabled,p_items:lines});if(error)throw error
    const o=Array.isArray(data)?data[0]:data;const mail=await sendReceiptBestEffort(sb,o,lines,trackingToken);
    return {order:{...publicOrder(o),trackingUrl:trackingToken&&Deno.env.get('SITE_URL')?`${Deno.env.get('SITE_URL')!.replace(/\/$/,'')}/track-order.html?t=${trackingToken}`:''},receiptAccepted:Boolean(mail?.id)}
  }catch(e){if(proofPath)await sb.storage.from('payment-proofs').remove([proofPath]).catch(()=>{});if((e as any)?.code==='23505'){const {data:existing}=await sb.from('orders').select('*').eq('client_request_hash',requestHash).maybeSingle();if(existing){const sameOwner=registered?existing.user_id===user!.id:(existing.customer_type==='guest'&&String(existing.customer_email||'').toLowerCase()===customerEmail&&normRef(String(existing.payment_reference||''))===normRef(reference));if(sameOwner){const trackingUrl=!registered&&existing.tracking_enabled&&Deno.env.get('SITE_URL')?`${Deno.env.get('SITE_URL')!.replace(/\/$/,'')}/track-order.html?t=${requestId}`:'';return {order:{...publicOrder(existing),trackingUrl},receiptAccepted:Boolean(existing.receipt_email_id),idempotent:true}}}throw Object.assign(new Error('This payment reference number has already been used.'),{status:409,code:'DUPLICATE_REFERENCE'})}if(String((e as any)?.message||'').toLowerCase().includes('duplicate'))throw Object.assign(new Error('This payment reference number has already been used.'),{status:409,code:'DUPLICATE_REFERENCE'});throw e}
}

function mlbbServerQuote(rateMap:Record<string,number>,q:any){const cap:any={Warrior:9,Elite:12,Master:16,Grandmaster:25,Epic:25,Legend:25,Mythic:25,'Mythical Honor':25,'Mythical Glory':50,'Mythical Immortal':999},order=Object.keys(cap);const a=order.indexOf(q.currentRank),b=order.indexOf(q.targetRank),cs=Number(q.currentValue),ts=Number(q.targetValue);if(a<0||b<0||b<a||!Number.isInteger(cs)||!Number.isInteger(ts)||cs<0||ts<0)throw Object.assign(new Error('Invalid MLBB quote.'),{status:400,code:'QUOTE_INVALID'});if(cs>cap[q.currentRank])throw Object.assign(new Error('Current stars do not match the selected rank.'),{status:400,code:'QUOTE_INVALID'});if(q.targetRank!=='Mythical Immortal'&&ts>cap[q.targetRank])throw Object.assign(new Error('Target stars do not match the selected rank.'),{status:400,code:'QUOTE_INVALID'});let pieces:any[]=[];if(a===b){if(ts<=cs)throw Object.assign(new Error('Target stars must be higher.'),{status:400,code:'QUOTE_INVALID'});pieces=[{tier:q.currentRank,units:ts-cs,rate:rateMap[q.currentRank]}]}else{const first=cap[q.currentRank]-cs;if(first>0)pieces.push({tier:q.currentRank,units:first,rate:rateMap[q.currentRank]});for(let i=a+1;i<b;i++)pieces.push({tier:order[i],units:cap[order[i]],rate:rateMap[order[i]]});if(ts>0)pieces.push({tier:q.targetRank,units:ts,rate:rateMap[q.targetRank]})}const units=pieces.reduce((a,x)=>a+x.units,0);if(units<=0)throw Object.assign(new Error('Target rank must be higher than current progress.'),{status:400,code:'QUOTE_INVALID'});if(pieces.some(x=>!Number.isFinite(x.rate)))throw Object.assign(new Error('Piloting rate configuration is incomplete.'),{status:409,code:'RATE_MISSING'});return {pieces,units,total:money(pieces.reduce((a,x)=>a+x.units*x.rate,0))}}
function codmServerQuote(rateMap:Record<string,number>,q:any){const order=['Rookie','Veteran','Elite','Pro','Master','Grandmaster','Legendary'],bounds:any={Rookie:[0,1000],Veteran:[1000,2000],Elite:[2000,3000],Pro:[3000,4500],Master:[4500,6000],Grandmaster:[6000,8000],Legendary:[8000,Infinity]};const a=order.indexOf(q.currentRank),b=order.indexOf(q.targetRank),cp=Number(q.currentValue),tp=Number(q.targetValue);if(a<0||b<0||b<a||!Number.isInteger(cp)||!Number.isInteger(tp)||cp<0||tp<0||tp<=cp)throw Object.assign(new Error('Invalid CODM quote.'),{status:400,code:'QUOTE_INVALID'});const cb=bounds[q.currentRank],tb=bounds[q.targetRank];if(cp<cb[0]||cp>=cb[1])throw Object.assign(new Error('Current points do not match the selected rank.'),{status:400,code:'QUOTE_INVALID'});if(q.targetRank==='Legendary'){if(tp<tb[0])throw Object.assign(new Error('Legendary target points must be at least 8000.'),{status:400,code:'QUOTE_INVALID'})}else if(tp<tb[0]||tp>=tb[1])throw Object.assign(new Error('Target points do not match the selected rank.'),{status:400,code:'QUOTE_INVALID'});let pieces:any[]=[],cursor=cp;for(let i=a;i<=b&&cursor<tp;i++){const tier=order[i],end=Math.min(tp,bounds[tier][1]),units=end-cursor;if(units>0)pieces.push({tier,units,rate:rateMap[tier]});cursor=end}if(cursor<tp)throw Object.assign(new Error('Invalid CODM rank progression.'),{status:400,code:'QUOTE_INVALID'});if(pieces.some(x=>!Number.isFinite(x.rate)))throw Object.assign(new Error('Piloting rate configuration is incomplete.'),{status:409,code:'RATE_MISSING'});return {pieces,units:tp-cp,total:money(pieces.reduce((a,x)=>a+x.units*x.rate,0))}}
async function pilotingAgreement(req:Request,body:any,signature:File|null){const sb=service(),{user}=await currentUser(req);const game=body.game==='Mobile Legends: Bang Bang'?'MLBB':body.game==='Call of Duty: Mobile'?'CODM':'';if(!game)throw Object.assign(new Error('Unsupported piloting game.'),{status:400,code:'VALIDATION'});const name=clean(body.fullName,120),email=clean(body.email,180).toLowerCase();if(!name||!email||!signature)throw Object.assign(new Error('Name, email and signature are required.'),{status:400,code:'VALIDATION'});if(!validEmail(email))throw Object.assign(new Error('Enter a valid email address.'),{status:400,code:'EMAIL_INVALID'});if(signature.type!=='image/png'||signature.size<=0||signature.size>1024*1024)throw Object.assign(new Error('Invalid signature image.'),{status:400,code:'SIGNATURE_INVALID'});const sigBytes=new Uint8Array(await signature.arrayBuffer());if(!validImageSignature(sigBytes,'image/png'))throw Object.assign(new Error('Invalid signature image content.'),{status:400,code:'SIGNATURE_INVALID'});const {data:rates,error}=await sb.from('piloting_rates').select('rank,rate').eq('game',game);if(error)throw error;const rm:any={};for(const r of rates||[])rm[r.rank]=Number(r.rate);const quote=game==='MLBB'?mlbbServerQuote(rm,body.quote):codmServerQuote(rm,body.quote);const sigPath=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}.png`;const {error:ue}=await sb.storage.from('piloting-signatures').upload(sigPath,sigBytes,{contentType:'image/png',upsert:false});if(ue)throw ue;const accountPayload={playerId:clean(body.playerId,120),facebookAccountName:clean(body.facebookAccountName,120),ign:clean(body.ign,120),mlbbAccountType:clean(body.mlbbAccountType,80),accountUsername:clean(body.accountUsername,180),codmUsername:clean(body.codmUsername,180)};const {data,error:ie}=await sb.from('piloting_agreements').insert({user_id:user?.id||null,customer_name:name,customer_email:email,game,quote_data:{...body.quote,pieces:quote.pieces,units:quote.units,total:quote.total},quoted_amount:quote.total,account_payload:accountPayload,signature_path:sigPath,agreement_version:clean(body.version,40)}).select('id,created_at,quoted_amount').single();if(ie){await sb.storage.from('piloting-signatures').remove([sigPath]);throw ie}return {agreementId:data.id,createdAt:data.created_at,quotedAmount:Number(data.quoted_amount)}}
async function myAccount(req:Request){const {user}=await currentUser(req);if(!user)throw Object.assign(new Error('Login required.'),{status:401,code:'LOGIN_REQUIRED'});const sb=service();const [profileRes,ordersRes,txRes]=await Promise.all([sb.from('profiles').select('*').eq('user_id',user.id).single(),sb.from('orders').select('*,order_items(*)').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100),sb.from('wallet_transactions').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(100)]);if(profileRes.error)throw profileRes.error;if(ordersRes.error)throw ordersRes.error;if(txRes.error)throw txRes.error;return {profile:profileRes.data,orders:ordersRes.data||[],transactions:txRes.data||[]}}
async function adminSnapshot(req:Request){const {sb}=await requireStaff(req);const [p,o,t,s,r]=await Promise.all([sb.from('profiles').select('*').order('created_at',{ascending:false}),sb.from('orders').select('*,order_items(*)').order('created_at',{ascending:false}).limit(500),sb.from('wallet_transactions').select('*').order('created_at',{ascending:false}).limit(500),sb.from('store_settings').select('*').eq('singleton',true).single(),sb.from('piloting_rates').select('*').order('game').order('sort_order')]);for(const x of [p,o,t,s,r])if(x.error)throw x.error;const products=await sb.from('products').select('*').order('id');if(products.error)throw products.error;return {profiles:p.data||[],orders:o.data||[],transactions:t.data||[],settings:s.data,rates:r.data||[],products:products.data||[]}}
async function adminAction(req:Request,body:any){const {user,role,sb}=await requireStaff(req);const action=clean(body.adminAction,50);const adminOnly=new Set(['product-upsert','product-delete','settings-save','rates-save','credit-adjust','user-status']);if(adminOnly.has(action)&&role!=='admin')throw Object.assign(new Error('Administrator permission is required for this action.'),{status:403,code:'FORBIDDEN'});
  if(action==='proof-url'){const {data:o}=await sb.from('orders').select('proof_path').eq('id',body.orderId).single();if(!o?.proof_path)throw Object.assign(new Error('No payment proof is attached.'),{status:404,code:'NO_PROOF'});const {data,error}=await sb.storage.from('payment-proofs').createSignedUrl(o.proof_path,120);if(error)throw error;return {url:data.signedUrl}}
  if(action==='update-order'){const {data:before,error:beforeError}=await sb.from('orders').select('status,proof_verified').eq('id',body.orderId).single();if(beforeError)throw beforeError;const {data,error}=await sb.rpc('admin_apply_order_update',{p_order_id:body.orderId,p_status:body.status,p_handler:clean(body.handler||'Unassigned',80),p_note:clean(body.note,900),p_proof_verified:Boolean(body.proofVerified),p_actor:user.id});if(error)throw error;const o=Array.isArray(data)?data[0]:data;const statusChanged=before.status!==o.status,proofJustVerified=!before.proof_verified&&o.proof_verified;try{if((statusChanged||proofJustVerified)&&String(o.customer_email||'').includes('@')){const displayStatus=!statusChanged&&proofJustVerified?'Payment Verified':o.status;const sent=await sendMail(o.customer_email,`Order update • ${o.invoice_no} • ${displayStatus}`,statusHtml({...o,status:displayStatus}));if(sent?.id)await sb.from('orders').update({last_status_email_id:sent.id}).eq('id',o.id)}}catch(e){console.error('status email failed',e)}return {order:o}}
  if(action==='product-upsert'){const p=body.product||{};const id=clean(p.id,100)||`PRD-${crypto.randomUUID().replace(/-/g,'').slice(0,8).toUpperCase()}`;const row={id,game:clean(p.game,20).toUpperCase(),region:clean(p.region||'GLOBAL',40).toUpperCase(),name:clean(p.name,160),category:clean(p.category||'DIGITAL PRODUCT',80).toUpperCase(),description:clean(p.description,1000),price:money(p.price),active:p.active!==false,stock_status:clean(p.stockStatus||'Available',30),catalog_type:clean(p.catalogType||'regular',30)};if(!row.name||!GAME_SET.has(row.game)||!STOCK_SET.has(row.stock_status)||!CATALOG_BY_GAME[row.game]?.has(row.catalog_type)||!Number.isFinite(row.price)||row.price<0||row.price>1000000)throw Object.assign(new Error('Invalid product details.'),{status:400,code:'VALIDATION'});if(!/^[A-Z0-9 _-]{1,40}$/.test(row.region))throw Object.assign(new Error('Invalid product region/server code.'),{status:400,code:'VALIDATION'});if(row.game==='MLBB'&&row.region==='US'&&row.catalog_type==='skin-gifting')throw Object.assign(new Error('MLBB US skin gifting is unavailable.'),{status:400,code:'UNAVAILABLE'});const {data,error}=await sb.from('products').upsert(row).select('*').single();if(error)throw error;return {product:data}}
  if(action==='product-delete'){const {error}=await sb.from('products').delete().eq('id',body.productId);if(error)throw error;return {ok:true}}
  if(action==='settings-save'){const s=body.settings||{};const {data,error}=await sb.from('store_settings').update({store_online:s.storeOnline!==false,announcement:clean(s.announcement,500),allow_wallet:s.allowWallet!==false,allow_bank:s.allowBank!==false,allow_gcash:s.allowGCash!==false,allow_paymaya:s.allowPayMaya!==false,updated_at:new Date().toISOString()}).eq('singleton',true).select('*').single();if(error)throw error;return {settings:data}}
  if(action==='rates-save'){const input=Array.isArray(body.rates)?body.rates:[];if(!input.length||input.length>30)throw Object.assign(new Error('Invalid rate list.'),{status:400,code:'VALIDATION'});const rows=input.map((x:any)=>({game:clean(x.game,10).toUpperCase(),rank:clean(x.rank,60),rate:Number(x.rate),unit:clean(x.unit,10),sort_order:Number(x.sortOrder||0),updated_at:new Date().toISOString()}));const games=[...new Set(rows.map((x:any)=>x.game))];if(games.length!==1||!PILOTING_SCHEMA[games[0]])throw Object.assign(new Error('Rates must update one supported game at a time.'),{status:400,code:'VALIDATION'});const schema=PILOTING_SCHEMA[games[0]],seen=new Set(rows.map((x:any)=>x.rank));if(rows.length!==schema.ranks.length||schema.ranks.some((r:string)=>!seen.has(r))||rows.some((x:any)=>!schema.ranks.includes(x.rank)||x.unit!==schema.unit||!Number.isFinite(x.rate)||x.rate<=0||x.rate>100000||!Number.isInteger(x.sort_order)||x.sort_order<1))throw Object.assign(new Error('Complete valid positive rates are required for every rank.'),{status:400,code:'VALIDATION'});const {error}=await sb.from('piloting_rates').upsert(rows);if(error)throw error;return {ok:true}}
  if(action==='credit-adjust'){const amount=Number(body.amount);if(!Number.isFinite(amount)||amount===0||Math.abs(amount)>1000000)throw Object.assign(new Error('Enter a valid non-zero credit adjustment up to ₱1,000,000.'),{status:400,code:'VALIDATION'});const {data,error}=await sb.rpc('admin_adjust_credits',{p_user_id:body.userId,p_amount:amount,p_reason:clean(body.reason,250),p_actor:user.id});if(error)throw error;return {profile:Array.isArray(data)?data[0]:data}}
  if(action==='user-status'){const status=clean(body.status,20);if(!['Active','On Hold','Suspended'].includes(status))throw Object.assign(new Error('Invalid status.'),{status:400,code:'VALIDATION'});const {data,error}=await sb.from('profiles').update({status}).eq('user_id',body.userId).select('*').single();if(error)throw error;return {profile:data}}
  if(action==='manual-order'){const x=body.order||{},inv=invoiceNo(),manualStatus=clean(x.status||'New Order',30);if(!['Awaiting Payment','New Order'].includes(manualStatus))throw Object.assign(new Error('New manual orders must start as Awaiting Payment or New Order.'),{status:400,code:'VALIDATION'});const row={invoice_no:inv,user_id:x.userId||null,customer_type:x.userId?'registered':'guest',customer_name:clean(x.customerName,120),customer_email:clean(x.customerEmail,180),customer_mobile:clean(x.customerMobile,40),account_number:clean(x.accountNumber,80)||null,order_type:'manual',game:clean(x.game||'OTHER',40),region:'GLOBAL',user_info:clean(x.userInfo,250),product_summary:clean(x.product,500),total_amount:money(x.amount),payment_method:'Manual',status:manualStatus,handler:clean(x.handler||'Unassigned',80),note:clean(x.note,900),catalog_type:'manual'};if(!row.customer_name||!row.product_summary||!Number.isFinite(row.total_amount)||row.total_amount<=0||row.total_amount>1000000)throw Object.assign(new Error('Customer, product and a valid amount are required.'),{status:400,code:'VALIDATION'});if(row.customer_email&&!validEmail(row.customer_email))throw Object.assign(new Error('Enter a valid customer email or leave it blank.'),{status:400,code:'EMAIL_INVALID'});const {data,error}=await sb.from('orders').insert(row).select('*').single();if(error)throw error;await sb.from('order_events').insert({order_id:data.id,status:data.status,public_message:'Order created by Surae staff.',actor_user_id:user.id});return {order:data}}
  throw Object.assign(new Error('Unknown admin action.'),{status:400,code:'UNKNOWN_ACTION'})
}

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,{error:'Method not allowed.'},405)
  try{const {body,file,signature}=await parse(req);const action=clean(body.action,50);const sb=service();let result:any;
    if(action==='bootstrap')result=await bootstrap(sb);
    else if(action==='auth-login')result=await authLogin(body);
    else if(action==='auth-register')result=await authRegister(body);
    else if(action==='checkout')result=await checkout(req,body,file);
    else if(action==='my-account')result=await myAccount(req);
    else if(action==='piloting-agreement')result=await pilotingAgreement(req,body,signature);
    else if(action==='admin-snapshot')result=await adminSnapshot(req);
    else if(action==='admin')result=await adminAction(req,body);
    else throw Object.assign(new Error('Unknown action.'),{status:400,code:'UNKNOWN_ACTION'});
    return json(req,result)
  }catch(e:any){console.error(e);const payload:any=safeError(e);const s=Number(payload.status||e?.status||500);delete payload.status;if(e?.balance!==undefined){payload.balance=e.balance;payload.required=e.required}return json(req,payload,s>=400&&s<600?s:500)}
})
